### PR TITLE
Query and update animals table

### PR DESCRIPTION
**Pull request by naji-97**
- [ ] In this project, I used transactions to update and delete records.
- [ ] also, I used my knowledge of aggregate functions and GROUP BY to answer analytical questions.
[update1](https://github.com/naji-97/Vet-Clinic-dataBases/blob/update-animals/img/Screenshot-update1.png)
[update2](https://github.com/naji-97/Vet-Clinic-dataBases/blob/update-animals/img/Screenshot-update2.png)
[delete](https://github.com/naji-97/Vet-Clinic-dataBases/blob/update-animals/img/Screenshot%20delete-1.png)

### CODE REVIEW

**Review by bobb-Rob — COMMENTED** [review]
Hi @naji-97,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is not following the correct flow which is [GitFlow.](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md). Kindly open a new pull request using the correct flow, i.e from a `feature` branch into the `dev/develop/development` branch. In addition, for re-reviews please always submit the pull request that was first reviewed so that the history is preserved. Lastly, I see that the [previous Pull request](https://github.com/naji-97/Vet-Clinic-dataBases/pull/1) was approved, then why is it still not completed on your dashboard? 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by naji-97** [comment]
for the previous request I sent it accidently it was the first day's PR

**Review by bobb-Rob — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED ♻️

Hi @naji-97, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.



 ## Highlights
✅ No Linter error
✅ Correct use of Gitflow
✅ Very descriptive Pull Request(PR)


 ## Required Changes ♻️

#### Your codes are nicely written but you did not provide screenshots of the queries, Kindly add screenshots to this Pull request description add label them nicely as you did with your query codes.

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by omarsalem7 — APPROVED** [review]
Hi @naji-97 😊, 
# STATUS: APPROVED! 🥇 💯 



Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
